from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from drama_plugin.contracts.asset import Asset, AssetType
from drama_plugin.contracts.audio import RoleDubbingRequest, RoleDubbingResult
from drama_plugin.contracts.context import ContextBuildRequest, DramaContextPatch, DramaRunContext
from drama_plugin.contracts.creation import Episode, Scene, Script, Shot, Work
from drama_plugin.contracts.media import Media, MediaResolveResult, MediaRestoreResult, MediaType
from drama_plugin.contracts.research import ClaimAssessment, ResearchEvidence, ResearchSource
from drama_plugin.contracts.voice import Voice, VoiceContent, VoiceResolveResult, VoiceSourceType, VoiceStatus


class MemoryProvider(Protocol):
    async def create_work(self, title: str, content: dict[str, Any], description: str | None = None) -> Work: ...
    async def get_work(self, work_id: str) -> Work: ...
    async def save_work(self, work_id: str, title: str, content: dict[str, Any], description: str | None = None) -> Work: ...
    async def bind_work_voice(self, work_id: str, speaker_key: str, voice_id: str, expected_version: int) -> Work: ...
    async def list_works(self) -> list[Work]: ...
    async def search_works(self, query: str) -> list[Work]: ...
    async def create_script(self, work_id: str, title: str, content: dict[str, Any]) -> Script: ...
    async def get_script(self, script_id: str) -> Script: ...
    async def save_script(self, script_id: str, title: str, content: dict[str, Any]) -> Script: ...
    async def list_scripts(self, work_id: str) -> list[Script]: ...
    async def create_episode(self, script_id: str, episode_no: int, title: str, content: dict[str, Any]) -> Episode: ...
    async def get_episode(self, episode_id: str) -> Episode: ...
    async def save_episode(self, episode_id: str, episode_no: int, title: str, content: dict[str, Any]) -> Episode: ...
    async def list_episodes(self, script_id: str, episode_no: int | None = None, title: str | None = None) -> list[Episode]: ...
    async def create_scene(self, episode_id: str, order: int, title: str, content: dict[str, Any], location: str | None = None) -> Scene: ...
    async def get_scene(self, scene_id: str) -> Scene: ...
    async def save_scene(self, scene_id: str, order: int, title: str, content: dict[str, Any], location: str | None = None) -> Scene: ...
    async def list_scenes(self, episode_id: str, order: int | None = None, location: str | None = None, character: str | None = None) -> list[Scene]: ...
    async def search_scenes(self, query: str, episode_id: str | None = None) -> list[Scene]: ...
    async def create_shot(self, scene_id: str, shot_no: str, content: dict[str, Any], title: str | None = None, shot_type: str | None = None) -> Shot: ...
    async def get_shot(self, shot_id: str) -> Shot: ...
    async def save_shot(self, shot_id: str, shot_no: str, content: dict[str, Any], title: str | None = None, shot_type: str | None = None) -> Shot: ...
    async def list_shots(self, scene_id: str, shot_no: str | None = None, shot_type: str | None = None, character: str | None = None) -> list[Shot]: ...
    async def search_shots(self, query: str, scene_id: str | None = None) -> list[Shot]: ...


class AssetProvider(Protocol):
    async def create_asset(self, work_id: str, asset_type: AssetType, name: str, content: dict[str, Any], episode_id: str | None = None, scene_id: str | None = None, shot_id: str | None = None, description: str | None = None, reference_media_ids: list[str] | None = None) -> Asset: ...
    async def get_asset(self, asset_id: str) -> Asset: ...
    async def save_asset(self, asset_id: str, name: str, content: dict[str, Any], description: str | None = None, reference_media_ids: list[str] | None = None) -> Asset: ...
    async def list_assets(self, asset_type: AssetType | None = None) -> list[Asset]: ...
    async def search_assets(self, query: str, asset_type: AssetType | None = None) -> list[Asset]: ...


class ResearchProvider(Protocol):
    async def search_sources(self, query: str) -> list[ResearchSource]: ...
    async def search_events(self, query: str) -> list[ResearchEvidence]: ...
    async def search_people(self, query: str) -> list[ResearchEvidence]: ...
    async def search_locations(self, query: str) -> list[ResearchEvidence]: ...
    async def verify_claim(self, claim: str) -> ClaimAssessment: ...


class ProductionProvider(Protocol):
    async def generate_image(self, prompt: str, reference_asset_ids: list[str] | None = None, reference_media_ids: list[str] | None = None, parameters: dict[str, Any] | None = None) -> Media: ...
    async def generate_video(self, prompt: str, start_frame_media_id: str | None = None, end_frame_media_id: str | None = None, reference_media_ids: list[str] | None = None, parameters: dict[str, Any] | None = None) -> Media: ...


class VoiceProvider(Protocol):
    async def import_voice(self, name: str, source_type: VoiceSourceType, source_uri: str, duration_ms: int, content: VoiceContent) -> Voice: ...
    async def get_voice(self, voice_id: str) -> Voice: ...
    async def search_voices(self, query: str | None = None, status: VoiceStatus | None = None) -> list[Voice]: ...
    async def update_voice(self, voice_id: str, content: VoiceContent, expected_version: int, name: str | None = None, status: VoiceStatus | None = None) -> Voice: ...
    async def resolve_voice(self, voice_id: str) -> VoiceResolveResult: ...
    async def download_voice(self, voice_id: str, destination: Path) -> VoiceResolveResult: ...


class RoleDubbingProvider(Protocol):
    async def generate_role_dubbing(self, request: RoleDubbingRequest) -> RoleDubbingResult: ...


class MediaProvider(Protocol):
    async def create_media(self, work_id: str, media_type: MediaType, source_ref: str, content: dict[str, Any], asset_id: str | None = None, shot_id: str | None = None, purpose: str | None = None) -> Media: ...
    async def get_media(self, media_id: str) -> Media: ...
    async def save_media(self, media_id: str, content: dict[str, Any], purpose: str | None = None) -> Media: ...
    async def list_media(self, media_type: MediaType | None = None, work_id: str | None = None, purpose: str | None = None, source_ref: str | None = None) -> list[Media]: ...
    async def import_media(self, work_id: str, media_type: MediaType, source_uri: str, content: dict[str, Any], asset_id: str | None = None, shot_id: str | None = None, purpose: str | None = None, source_ref: str | None = None, duration_ms: int | None = None) -> Media: ...
    async def resolve_media(self, media_id: str) -> MediaResolveResult: ...
    async def download_media(self, media_id: str, destination: Path) -> MediaResolveResult: ...
    async def restore_media_object(self, media_id: str, source_uri: str) -> MediaRestoreResult: ...


class ContextProvider(Protocol):
    async def build_context(self, request: ContextBuildRequest) -> DramaRunContext: ...
    async def refresh_context(self, request: ContextBuildRequest, current: DramaRunContext) -> DramaContextPatch: ...
