from __future__ import annotations

from typing import Any, Protocol

from drama_plugin.contracts.asset import Asset, AssetType
from drama_plugin.contracts.context import ContextBuildRequest, DramaContextPatch, DramaRunContext
from drama_plugin.contracts.creation import Episode, Scene, Script, Shot, Work
from drama_plugin.contracts.media import Media, MediaType
from drama_plugin.contracts.research import ClaimAssessment, ResearchEvidence, ResearchSource


class MemoryProvider(Protocol):
    async def create_work(self, title: str, description: str | None = None, content: dict[str, Any] | None = None) -> Work: ...
    async def get_work(self, work_id: str) -> Work: ...
    async def save_work(self, work: Work) -> Work: ...
    async def list_works(self) -> list[Work]: ...
    async def search_works(self, query: str) -> list[Work]: ...
    async def create_script(self, work_id: str, title: str, content: dict[str, Any] | None = None) -> Script: ...
    async def get_script(self, script_id: str) -> Script: ...
    async def save_script(self, script: Script) -> Script: ...
    async def list_scripts(self, work_id: str) -> list[Script]: ...
    async def create_episode(self, script_id: str, number: int, title: str, content: dict[str, Any] | None = None) -> Episode: ...
    async def get_episode(self, episode_id: str) -> Episode: ...
    async def save_episode(self, episode: Episode) -> Episode: ...
    async def list_episodes(self, script_id: str, episode_no: int | None = None, title: str | None = None) -> list[Episode]: ...
    async def create_scene(self, episode_id: str, number: int, heading: str, content: dict[str, Any] | None = None) -> Scene: ...
    async def get_scene(self, scene_id: str) -> Scene: ...
    async def save_scene(self, scene: Scene) -> Scene: ...
    async def list_scenes(self, episode_id: str, order: int | None = None, location: str | None = None, character: str | None = None) -> list[Scene]: ...
    async def search_scenes(self, query: str, episode_id: str | None = None) -> list[Scene]: ...
    async def create_shot(self, scene_id: str, number: int, description: str, duration_seconds: float | None = None, content: dict[str, Any] | None = None) -> Shot: ...
    async def get_shot(self, shot_id: str) -> Shot: ...
    async def save_shot(self, shot: Shot) -> Shot: ...
    async def list_shots(self, scene_id: str, shot_no: int | None = None, shot_type: str | None = None, character: str | None = None) -> list[Shot]: ...
    async def search_shots(self, query: str, scene_id: str | None = None) -> list[Shot]: ...


class AssetProvider(Protocol):
    async def create_asset(self, asset_type: AssetType, name: str, description: str | None = None, reference_media_ids: list[str] | None = None) -> Asset: ...
    async def get_asset(self, asset_id: str) -> Asset: ...
    async def save_asset(self, asset: Asset) -> Asset: ...
    async def list_assets(self, asset_type: AssetType | None = None) -> list[Asset]: ...
    async def search_assets(self, query: str, asset_type: AssetType | None = None) -> list[Asset]: ...


class ResearchProvider(Protocol):
    async def search_sources(self, query: str) -> list[ResearchSource]: ...
    async def search_events(self, query: str) -> list[ResearchEvidence]: ...
    async def search_people(self, query: str) -> list[ResearchEvidence]: ...
    async def search_locations(self, query: str) -> list[ResearchEvidence]: ...
    async def verify_claim(self, claim: str) -> ClaimAssessment: ...


class ProductionProvider(Protocol):
    async def generate_image(self, prompt: str, reference_asset_ids: list[str] | None = None, reference_media_ids: list[str] | None = None, parameters: dict[str, Any] | None = None) -> Media: ...
    async def generate_video(self, prompt: str, start_frame_media_id: str | None = None, end_frame_media_id: str | None = None, reference_media_ids: list[str] | None = None, parameters: dict[str, Any] | None = None) -> Media: ...
    async def generate_audio(self, prompt: str, reference_media_ids: list[str] | None = None, parameters: dict[str, Any] | None = None) -> Media: ...


class MediaProvider(Protocol):
    async def create_media(self, media_type: MediaType, mime_type: str, storage_key: str, metadata: dict[str, Any] | None = None) -> Media: ...
    async def get_media(self, media_id: str) -> Media: ...
    async def save_media(self, media: Media) -> Media: ...
    async def list_media(self, media_type: MediaType | None = None) -> list[Media]: ...


class ContextProvider(Protocol):
    async def build_context(self, request: ContextBuildRequest) -> DramaRunContext: ...
    async def refresh_context(self, request: ContextBuildRequest, current: DramaRunContext) -> DramaContextPatch: ...
