"""R2 authored DESIGN_FIXTURE_ONLY data, never formal Gaixia or actual AV evidence."""
from __future__ import annotations
from typing import Any, Literal
from pathlib import Path
import hashlib
from drama_plugin.contracts.base import dump_contract, sha256_canonical as fp
from drama_plugin.contracts.dpd import SceneDPD, BeatDPD, LineDPD, DPDLayerState, PerformanceLevel
from drama_plugin.dpd import compose_dpd
from drama_plugin.contracts.performance_direction import DirectorPerformanceIntent, PerformanceProjection, PerformanceObservation, BeatCoordination
from drama_plugin.contracts.audio import VoiceProfile, CreativeVoiceProfile, TargetTimingPolicy
from drama_plugin.contracts.sequence import FilmReview, PlaybackObservation
from drama_plugin.visual.performance import project_visual_performance, build_realized_performance_snapshot
from drama_plugin.audio.projection import compile_projected_speech_request
from drama_plugin.performance_direction import NATIVE_DIMENSIONS

CASES: dict[str, dict[str, Any]] = {
'P03': dict(text='骓不逝兮可柰何，虞兮虞兮柰若何！', line='N05', actor='xiang-yu', target='虞美人',
 purpose='接受亲近者的回应，不替二人的未来作答', objective='向眼前的虞求回应，并听完她的回应', obstacle='无法给亲近者安排确定未来', tactic='从自陈转为向她发问', subtext='我仍有力量，却答不了你的未来',
 core='情绪穿过了控制，控制没有消失。他终于把问题交给眼前的人；泪可以留下，身体继续承担听她回应的责任。',
 audience='看到强者愿意被一个具体的人留住，不观看一次崩溃', focus='虞的回应', expression='LOW', load='LOW', spatial='眼前一人', breath='有支撑的平稳气息',
 body='坐处承重不变；胸廓仍能支撑声音，泪落不带动肩部下塌', eyes='从帐外收回注意；唱到虞兮时眼睛真正抵达她，和唱期间不重新看出口', hands='抬杯的手停在能继续持杯的位置；不抖、不反复抹脸。此刻不擦泪，因为双手仍在持杯，注意力要留给回应者', movement='只允许杯手的一次停顿；不向天伸臂、不摇头', voice='此前N04自陈力量有身体支撑；时不利开始收束。当前N05由骓转到虞，声音抵达眼前人，仍清楚有气，不人工耳语',
 attack='保留字头，不用哭音挤出虞字', emphasis='虞兮是对象转换，重心落在发问，不把每个兮都拖成长叹', closure='若何留给她回答；自身声音结束后不覆盖她的和唱', pause='停顿等待虞完成回应，不每句固定长停顿',
 release=['controlled_tear','hand_pause'], forbidden=['sobbing','collapse','continuous_shaking','funeral_tone','shouted_lament','artificial_whisper','exaggerated_voice_break'],
 out='完成相处后可恢复行动基线；不把一滴泪延续成全片忧郁脸与哭腔',
 events={'gaze_returns':2000,'yu_phrase_start':2000,'own_voice_end':3500,'partner_voice_start':3600,'partner_response_end':7500,'tear_at':5500,'hand_pause_at':5700,'rise_start':8000},
 rules=[('gaze_returns','NOT_AFTER','yu_phrase_start',None,'唱到虞兮时注意必须已到虞'),('own_voice_end','NOT_AFTER','partner_voice_start',None,'不能以自己的声尾覆盖虞和唱'),('tear_at','WITHIN','partner_voice_start','partner_response_end','泪落属于听她回应'),('hand_pause_at','WITHIN','partner_voice_start','partner_response_end','手停是在听，不是抖'),('rise_start','NOT_BEFORE','partner_response_end',None,'准备起身不得抢走尚未完成的回应')]),
'P08': dict(text='何如？',line='s7-how',actor='xiang-yu',target='亲历快战的从骑',purpose='兑现个人能力并得到真实同伴认可，局部胜利不能逆转战局',objective='向亲历者索取刚刚战果的确认',obstacle='赢得眼前交战却没有恢复战争主动权',tactic='先兑现，再直接向他们发问',subtext='你们亲眼看见了',core='这次高兴是真的。身体先收回战斗中的那口气，才把问题交给同伴；认可到了，笑有自己的完整时间。远处后果随后进入。',audience='获得被挣出的战斗快意，之后才看见胜利的限度',focus='身旁同伴的认可',expression='MEDIUM',load='HIGH',spatial='身边这圈从骑',breath='战后短促恢复',body='胸廓短暂打开，站稳后允许呼气；不假装体力没有损耗',eyes='看刚同自己打过来的从骑，不仰天寻找观众',hands='手回到可掌缰的位置，不抖兵器作为笑的附件',movement='一次短暂打开后停留，不把真实笑改成张臂狂笑',voice='有刚打赢后的生命力，问的是亲历者；战后仍有恢复气息，不虚弱、不苦涩、不像临终遗言',attack='以真实呼气后的短起句进入何如，字头清楚而不宣告',emphasis='问句把回答权给同伴，不拉长何字作痛苦呻吟',closure='问完留给同伴回答；得到认可后不补一段自己的大笑声',pause='只等实际回答，不提前给悲剧尾声空拍',release=['real_smile','one_breath_release'],forbidden=['bitter_smile','bitter_laugh','hysterical_laugh','skyward_laugh','evil_smirk','instant_tragic_collapse','funeral_tone','unbroken_ceremonial_breath'],out='笑的Beat完成，追兵新信息才使行动重新收束；并非从此无压力',events={'question_end':1800,'partner_response_end':3500,'smile_start':3600,'smile_end':5500,'consequence_enters':6500},rules=[('smile_start','NOT_BEFORE','partner_response_end',None,'笑须来自同伴认可'),('consequence_enters','NOT_BEFORE','smile_end',None,'不可立刻取消真实快乐')]),
'P09': dict(text='我带江东八千子弟渡江西来，如今一个也没带回去。父兄便肯再立我，我又拿什么脸面见他们？',line='s8-refuse',actor='xiang-yu',target='正在劝渡的亭长',purpose='面对真实可用的生路作出拒绝，承担后果',objective='向认真救自己的人解释为何不接受再立',obstacle='生路可行，而自我判断无法容纳再次面对父兄',tactic='听清方案，再说明不接受的理由',subtext='你给的路存在，我不肯替自己走进去',core='他来到的是一条还走得通的路。先听、靠近、考虑，再回应。拒绝是这次交谈中做出的选择，不能进场就戴着必死的表情。',audience='承认生还本来可能，才承担拒渡的重量',focus='亭长给出的现实帮助',expression='LOW',load='HIGH',spatial='船边的亭长',breath='疲劳但继续支撑短句',body='亭长说话时身体允许向船走近；听清后才停下，不提前横身拒绝',eyes='先认船的落脚处，再回亭长脸上，不能对江朗诵',hands='随后交缰要等亭长握稳才放，赠马是照料而非慢动作诀别仪式',movement='只让回应后的停步显出拒绝；不提前摆悲壮姿态',voice='向正在救自己的人说明不接受的原因。父兄便肯再立我是让步，不是对江发表遗言',attack='先接住亭长的话再开口，不用第一字哭声替代思考',emphasis='重心是便肯和我，区分他人的可能接纳与自己的不肯',closure='问句收给亭长，留出船就在这里的再次坚持；不作死亡宣言式长尾',pause='在对方说完后回应；句内只为话意转折和疲劳换气，不每句悲停',release=['one_physical_pause'],forbidden=['crying_from_first_line','funeral_tone','heroic_declamation','tragic_tail_each_sentence','whisper_of_death','unbroken_ceremonial_breath'],out='拒绝之后仍能耐心照料马和完成交接，不把选择变成失去行动能力',events={'boatman_end':1500,'approach_start':1000,'response_start':1900,'refusal_visible':2200,'boatman_grip_secure':7500,'rein_release':7800},rules=[('response_start','NOT_BEFORE','boatman_end',None,'先听清真实劝渡才回应'),('refusal_visible','NOT_BEFORE','boatman_end',None,'拒绝不得预置'),('rein_release','NOT_BEFORE','boatman_grip_secure',None,'交缰等待对方握稳')]),
}
# Generic authored situations share mechanisms, not historical people or events.
CASES['intimate']={**CASES['P03'],'text':'你把话说完，我在听。','line':'line-listen','actor':'repairer','target':'要离开的搭档','purpose':'一次工作交接中允许搭档说出未完的话','objective':'听完搭档的交接条件','obstacle':'自己急于结束争执','tactic':'停止整理工具，将回应权交给搭档','subtext':'我不再用手里的工作躲开你','core':'他仍握稳工具，只停止继续收拾。眼泪可以出现，任务没有被抛下；先把对方的话听完。','audience':'看到一个行动惯性很强的人愿意接收反对意见','focus':'搭档未完的交接','body':'承重脚与托工具的肩保持稳定，不塌下','eyes':'从工作台回到搭档脸上','hands':'工具留在安全支撑处，手停但不颤抖','voice':'普通近距离对话，气息有支撑，强调你把话说完而不是我的委屈','attack':'清楚起句，不用抽泣前导','emphasis':'把话说完把发言权交给对方','closure':'收住自己声尾等待搭档，不续说补偿性安慰','events':{'own_voice_end':2500,'partner_voice_start':2800,'partner_response_end':7000,'resume_work':7500},'rules':[('own_voice_end','NOT_AFTER','partner_voice_start',None,'不能覆盖搭档'),('resume_work','NOT_BEFORE','partner_response_end',None,'先听完再继续工作')],'out':'回应结束后恢复工作状态，不带永久悲伤滤镜'}
CASES['victory']={**CASES['P08'],'text':'看见了吗？','line':'line-victory','actor':'rescue-leader','target':'共同完成救援的队员','purpose':'救援成功的短暂真实释放，然后恢复值守','objective':'让共同完成任务的人确认结果','obstacle':'危险刚解除，身体还未恢复','tactic':'看向亲历同伴直接求证','subtext':'我们真的做到了','core':'允许真实高兴。先向共同完成的人确认，再呼一口气笑出来；值守的新信息不能抢走这一刻。','audience':'共同努力的兑现','focus':'队员的认可','body':'卸下用力后的肩部紧绷，胸廓打开但仍站稳','eyes':'看共同救援者，不朝天大笑','hands':'先把工具放到安全处，手不挥舞庆功','voice':'刚完成高负荷行动，短问有生命力但仍需换气','attack':'恢复一口气后短促问出看见了吗，不作庆功宣告','emphasis':'看见把注意力交给共同经历者，吗保持真实询问','out':'笑过后接到新的值守信息，重新行动；快乐没有抹掉身体负荷'}
CASES['decision']={**CASES['P09'],'text':'让我再看一遍撤离路线。','line':'line-choice','actor':'station-chief','target':'递来撤离方案的同事','purpose':'在真实可行的撤离方案前完成选择','objective':'听明白可执行方案再决定','obstacle':'责任与风险并存，不能靠先入结论跳过信息','tactic':'请求复核路线而非宣布牺牲','subtext':'你的方案可能有效，我要先确认','core':'高压不是预设赴死。他先听方案并靠近地图，再提出需要核实的问题；身体与声音都保留被说服的可能。','audience':'先看到真实选择存在','focus':'同事带来的可执行方案','body':'向地图靠近而不退到宣告位置','eyes':'看路线再看解释的人，不对远方发表演说','hands':'把图纸交回前等同事接稳','voice':'对眼前同事提出真实复核请求，不作领袖宣言','attack':'听完后直接起句','emphasis':'再看一遍是实际请求，不是绝望拖延','closure':'把解释权交给同事','events':{'partner_end':1500,'line_start':1900,'partner_grip':7500,'map_release':7800},'rules':[('line_start','NOT_BEFORE','partner_end',None,'先听完方案'),('map_release','NOT_BEFORE','partner_grip',None,'交图等对方接稳')],'out':'决定仍须承担后果；不因一次停顿变成全场死亡模式'}


CASES['P03-strength'] = {**CASES['P03'], 'text':'力拔山兮气盖世，时不利兮骓不逝。', 'line':'N04', 'eyes':'前段仍被帐外声牵引；时不利处收回注意，为下一段转向虞准备，不提前演完失落', 'hands':'持杯保持稳定，不提前表演听虞回应时的手停', 'movement':'承重姿态支撑起句；收束发生在气息和注意，不添加悲恸动作', 'voice':'力拔山兮有身体支撑与向外力量，时不利兮开始收束但不虚弱；不能第一句就是葬礼。', 'attack':'起句干净有支撑，不以哽咽开头', 'emphasis':'由力拔山的自陈走向时不利的受阻，不将两段唱成同一哭腔', 'closure':'收束而不衰败，为下一段面向虞的发问留下动作联系', 'release':[], 'events':{'strength_phrase_end':3000,'constriction_start':3200}, 'rules':[('constriction_start','NOT_BEFORE','strength_phrase_end',None,'自陈力量先成立，再面对失势')]}


def make_case(name: str, route: Literal['stylized_cinematic_cg', 'live_action'] = 'stylized_cinematic_cg', proposal_path: Path | None = None,
              grammar_path: Path | None = None) -> dict[str, Any]:
    c=CASES[name]; scene='fixture:'+('P03' if name=='P03-strength' else name); beat=scene+(':strength' if name=='P03-strength' else ':critical'); speaker='speaker:'+c['actor']
    source=hashlib.sha256(proposal_path.read_bytes()).hexdigest() if proposal_path and name.startswith('P') else fp({'fixture':name,'text':c['text'],'purpose':c['purpose']})
    if proposal_path and name.startswith('P'):
        assert c['text'] in proposal_path.read_text(), 'R1 fixture text changed'
    source_key='r1-proposal' if name.startswith('P') else 'generic:'+name
    state=DPDLayerState(objective=c['objective'],interaction_target=c['target'],tactic=c['tactic'],authority_position='equal in this exchange',relationship_stance='target-directed exchange with continuing mutual attention',internal_activation=PerformanceLevel.HIGH,external_control=PerformanceLevel.HIGH,public_private_context='private or bounded present partners',subtext=c['subtext'],performance_boundaries=('No invented dialogue or private historical fact.',))
    dpd=compose_dpd(SceneDPD(scene_id=scene,source_fingerprint=source,dramatic_purpose=c['purpose'],conflict_condition=c['obstacle'],power_structure='role authority does not erase the listener',direction=state),BeatDPD(scene_id=scene,beat_id=beat,actor=speaker,obstacle=c['obstacle'],transition_trigger='partner finishes a material response',direction=DPDLayerState(objective=c['objective'])),LineDPD(scene_id=scene,beat_id=beat,spoken_content_id=c['line'],speaker=speaker,dramatic_action=c['tactic'],observable_intent=c['objective'],continuity='specific exchange follows the previous action',change_from_previous='attention now belongs to the partner'))
    cues=tuple(BeatCoordination(beat_id=beat,spoken_content_id=c['line'],event=e,relation=r,anchor=a,end_anchor=z,reason=why) for e,r,a,z,why in c['rules'])
    intent=DirectorPerformanceIntent(scene_id=scene,source_fingerprints={source_key:source},dpd_fingerprints=(dpd.fingerprint,),beat_ids=(beat,),performance_core=c['core'],audience_experience=c['audience'],primary_focus=c['focus'],containment='内压可以高，动作和声音不可因此自动放大',external_expression_ceiling='MEDIUM',permitted_release=tuple(c['release']),release_point='由眼前同伴的具体行动触发；见协调事件',partner_focus=c['target'],performance_rhythm='完成接收、回应与释放后才进入下一个动作',continuity_in='保留人物能行动、能听的基线；不提前进入死亡模式',continuity_out=c['out'],do_not=tuple(c['forbidden']),forbidden_behaviors=tuple(c['forbidden']),coordination=cues,review_basis='DESIGN_FIXTURE_ONLY')
    grammar=hashlib.sha256(grammar_path.read_bytes()).hexdigest() if grammar_path else fp({'fixtureGrammar':route})
    current={source_key:source,'grammar:'+route:grammar}
    vi=dict(body_state=c['body'],posture='保持当前任务需要的承重，不用情绪替代受力',weight='重心改变只为下一实际动作，不自动晃动',movement=c['movement'],eyes=c['eyes'],head='眼的目标改变后，头才按需要跟随；不固定点头',hands=c['hands'],visible_breath=c['breath'],prop=c['hands'],partner=c['target'],distance=c['spatial'],timing='；'.join(x.reason for x in cues),release=('；'.join(c['release'])+'：在对应触发事件允许，不延长成全场表演状态') if c['release'] else '此Beat不新增泪落、手停或声音破裂；先建立自陈力量',continuity=c['out'],do_not='；'.join(c['forbidden']))
    if route=='stylized_cinematic_cg':vi['movement']+='；按既有CG语法保持姿态与轮廓可读，一次只让有信息的部位变化'
    else:vi['movement']+='；真人身体保留自然微调，不要求CG轮廓强化或面部形变'
    ai=dict(voice_core=c['voice'],interaction='只向'+c['target']+'说',spatial_projection=c['spatial'],pace='自然语速，依言语行动变化，不按情绪统一放慢',rhythm='自陈、接收和回应各有节奏；不每句相同停顿',intensity='有行动力度，但不把内压换成哭喊',breath_support=c['breath'],phrase_attack=c['attack'],articulation='词义清楚，保留字头；不为高情绪吞字',emphasis=c['emphasis'],pause_function=c['pause'],sentence_closure=c['closure'],coloration='状态作用在气息与收句，保持同一说话人身份',release=('；'.join(c['release'])+'；声音只按该Beat需要参与，不能覆盖同伴') if c['release'] else '不新增哭腔或声音破裂；由有支撑的起句逐步收束',continuity=c['out'],do_not='；'.join(c['forbidden']))
    common=dict(director_intent_fingerprint=fp(intent),beat_id=beat,spoken_content_id=c['line'],interaction_target=c['target'],spatial_projection=c['spatial'],external_expression=c['expression'],external_control='HIGH',body_load=c['load'],breath=c['breath'],release=tuple(c['release']),continuity_in=intent.continuity_in,continuity_out=intent.continuity_out,coordination=cues)
    vp=PerformanceProjection(**common,channel='VISUAL',instructions=vi,route=route,grammar_fingerprint=grammar)
    ap=PerformanceProjection(**common,channel='VOICE',instructions=ai)
    visual=project_visual_performance(dpd_snapshot=dpd,shot_id=scene+':coverage-fixture',shot_scene_id=scene,shot_fingerprint=fp('local coverage fixture, not formal Shot'),shot_spoken_content_ids=(c['line'],),shot_character_keys=(speaker,),primary_character_key=speaker,character_identity_key=speaker,character_visual_identity_fingerprint=fp(speaker),scene_visual_identity_fingerprint=fp(scene),director_intent=intent,performance_projection=vp,current_fingerprints=current)
    voice=VoiceProfile(profile_id='fixture-profile:'+c['actor'],speaker_key=speaker,creative_profile=CreativeVoiceProfile(vocal_age='MATURE_ADULT',vocal_weight='MEDIUM',resonance_depth='BALANCED',texture='CLEAN_SUBTLE_GRAIN',baseline_pace='MODERATE',articulation_firmness='FIRM'))
    spoken={'id':c['line'],'speakerKey':speaker,'text':c['text']}
    request=compile_projected_speech_request(work_id='fixture-work',dpd_snapshot=dpd,spoken_content=spoken,voice_profile=voice,voice_identity_ref='fixture-voice:'+c['actor'],timing_policy=TargetTimingPolicy(policy='NATURAL'),director_intent=intent,performance_projection=ap,current_fingerprints=current)
    media_hash=fp({'DESIGN_FIXTURE_ONLY':name,'route':route})
    obs=dict(beat_id=beat,spoken_content_id=c['line'],speaker_key=speaker,media_hash=media_hash,method='DESIGN_FIXTURE',observer='offline authored counterexample, not playback',evidence_ref='fixture:'+name+':explicit-assumptions',start_ms=0,end_ms=10000,external_expression=c['expression'],external_control='HIGH',interaction_target=c['target'],spatial_projection=c['spatial'],body_load=c['load'],breath=c['breath'],release=tuple(c['release']),continuity_in=intent.continuity_in,continuity_out=intent.continuity_out,meaning_preserved='PASS')
    audio_keys={'yu_phrase_start','own_voice_end','partner_voice_start','partner_response_end','question_end','boatman_end','response_start','partner_end','line_start','strength_phrase_end','constriction_start'}
    vo=PerformanceObservation(**obs,channel='VISUAL',event_times_ms={k:v for k,v in c['events'].items() if k not in audio_keys})
    ao=PerformanceObservation(**obs,channel='VOICE',event_times_ms={k:v for k,v in c['events'].items() if k in audio_keys})
    rp=build_realized_performance_snapshot(dict(videoMediaId='fixture-media:'+name,videoContentHash=media_hash,shotId=visual.shot_id,videoDurationMs=10000,observedSpeakerKey=speaker,shotScale='design fixture; no rendered image',speakerScreenPresence='fixture-visible speaker',speakerOrientation=c['target'],gazeDirection=c['eyes'],headMotion='authored fixture observation',bodyMotion=c['body'],visibleActivation=c['expression'],facialTension='LOW',expressionChange='PRESENT',gestureActivity=c['hands'],interactionDistance=c['spatial'],preSpeechAction='hear partner',mouthActivity='UNKNOWN',postSpeechAction=c['out'],performanceObservations=[dump_contract(vo)]))
    review=FilmReview(media_hash=media_hash,duration=10,performance_review_basis='DESIGN_ONLY',performance_required_beats=(beat+'#'+c['line'],),performance_observations=(ao,),native_audio_suitability={k:'PASS' for k in NATIVE_DIMENSIONS})
    return dict(name=name,config=c,dpd=dpd,intent=intent,current=current,visual=visual,audio=request.audio_performance_brief,request=request,spoken=spoken,realized=rp,review=review,visual_observation=vo,voice_observation=ao)
