"""Generic authored DESIGN_FIXTURE_ONLY / NOT HISTORICAL CLAIM cases."""
from drama_plugin.contracts.base import dump_contract
from drama_plugin.contracts.preproduction import *
from drama_plugin.contracts.dramatic_editorial import EditorialRhythmPlan, ShotTransition
from drama_plugin.contracts.dpd import SceneDPD
from drama_plugin.contracts.cinematic import SourceSoundIntent, VisualBible
from drama_plugin.contracts.visual_route import RouteContext
from drama_plugin.contracts.production_design import CharacterVisualSpec
from drama_plugin.director import pin

CASES = {
'war':dict(title='撤渡',carrier='守桥者与负伤同伴：先走会遗弃所保护的人，久留会失去整队',counter='从催人加速到亲自接过别人的重量，胜利愿望让位于把人带走',intent='先看懂窄渡容量，再期待最后一人过岸，保留未归者的代价',object='担架',costume='深赭布衬与分层皮甲；肩部承重磨白，抬举袖口不拖地',scale='近处四个行动层与远处追队分组，军阵不能遮掉通路',scenes=[('夜间渡屋','队长把可行走者排到后面，伤者问担架是否挤掉别人；队长让出自己的位置。','队长先解包裹，等担架抬起才离门；伤者看空出的凳位不追加解释。'),('夜间堤口','后列让出窄口，盾手留住追势，担架先过；侧路泥滑只能依次退出。','盾手退半步吸收冲力，背向同伴守通道；抬者膝软时队长接重，不设计单人抛开敌阵。'),('黎明对岸','队伍渡过，一名守桥者未归；队长接过空担架，将新伤者放到为未归者留的位置。','先留出一人距离，手搭空担架不马上放；听见伤者呼吸才转手抬起，不报胜利。')]),
'relationship':dict(title='留下钥匙',carrier='母亲与成年女儿：远行机会会使小铺失去帮手；相互照料与自主选择相冲',counter='把照料理解为留住，逐渐承认放手也能照料；无爱情线',intent='先误读收钥匙为阻拦，最后从主动让门看懂改变',object='钥匙',costume='母亲靛灰补缝围衣，女儿同材短外衣；袖口洁净，肘部磨损，领边细线有尊严',scale='两人的手与门槛关系足够，不加哭诉与人群',scenes=[('夜间小铺','女儿收行囊，母亲仍分两份面粉；女儿放钥匙，母亲把它压在账下。','女儿看两份粉，母亲手不停但不抬头；钥匙轻响后两人不补解释。'),('夜间门槛','雨水入门，母亲拿旧鞋堵缝；女儿伸手取，母亲松手并让开门口。','伸手一半停住，母亲先移开身体再松手，不互相推拉；目光由鞋转到门。'),('黎明门外','母亲交干布包、自己留钥匙；女儿独行，母亲回铺只摆一份面粉。','等母亲握稳钥匙才转身；母亲不抢行囊，呼一口气后移动第二只碗。')]),
'political':dict(title='封印之前',carrier='掌印者与属吏：虚报可保官位，却把缺粮责任推给百姓；信任与自保冲突',counter='公开程序掩盖私下责任，属吏把真账放回，逼主官自己承担签字',intent='让印的可达距离表达权力，高潮是手从遮账到把账推给见证者',object='印与账册',costume='主官暗青细密领缘，属吏同色粗织窄袖，来使腰带标职责；不加奇幻勋章',scale='谁能接近真账表达权力；不靠宫殿大小或轮流发言',scenes=[('夜间议室','两本仓粮数目相反；主官把印放在真账上阻止取走。','属吏翻到差额页，收手等主官看；主官盖住页边不急训话，见证者继续坐。'),('夜间廊下','来使催立即封印；属吏抱账停门口，主官必须离席读最后一页。','来使占通道，属吏将账转向主官不瞪人；主官起身，其他人不自动齐起。'),('黎明公案','主官把真账递给见证者再盖印；来使收预写告示离去，属吏继续登记责任。','先松账页再取印，不重砸；先见来使卷纸的反应，留住属吏书写的后果。')])}


def make_case(name='war', route='stylized_cinematic_cg', formal=None):
    c=CASES[name]; artifacts={}; current={}
    def keep(key,obj):
        value=dump_contract(obj) if hasattr(obj,'model_dump') else obj
        ref=pin(name+':'+key,value); artifacts[ref.key]=value; current[ref.key]=ref.fingerprint
        return ref
    scenes=tuple(name+str(i+1) for i in range(3))
    source=keep('source',dict(label='DESIGN_FIXTURE_ONLY / NOT HISTORICAL CLAIM',case=c)); pins=(source,)
    if formal:
        from drama_plugin.contracts.sequence import SourcePin
        pins=tuple(SourcePin(key=k,fingerprint=v,kind='CANON') for k,v in formal['formal_source'].pins.items())
        source=pins[0];current.update(formal['formal_source'].pins)
    intent=keep('intent',dict(intent=c['intent'])); route_ref=keep('route',RouteContext.model_validate(dict(project=dict(workId=name,revision='r1',visualRoute=route,enabledRoutes=[route]),sequence=dict(workId=name,sequenceKey=name,visualRoute=route,overrideReason='explicit fixture route'),style=dict(visualRoute=route,revision='r1',medium='DESIGNED_CG' if route=='stylized_cinematic_cg' else 'PHOTOGRAPHIC',rendering='text design only',castingCriteria=['role readability'],shapeLanguage='occupation and mass',materialPalette='cloth wood leather',cameraGrammar='motivated spatial relations',performanceGrammar='listening before action',historicalBoundary='DESIGN_FIXTURE_ONLY',forbiddenDrifts=['fantasy']))) )
    reasons=dict(historical_causality='虚构素材，不归属于真实人物；三次行动的因果明确',narrative_spine=c['intent'],protagonist_decision_arc=c['scenes'][0][1]+' → '+c['scenes'][2][1],character_arc=c['counter'],human_stakes=c['carrier'],emotional_counterline=c['counter'],internal_external_conflict=c['carrier'],scene_variety='室内建立义务→门口行动检验→黎明公开承担',scene_necessity='删起场失责任起点，删中场无阻力，删末场无后果',setup_payoff=c['object']+'从被控制物件转成承担关系',dialogue='无新解释台词，任务与停顿区分人物',literary_opportunity='物件行为承担意涵，默认无作者旁白',action_drama_balance=c['scale'],climax_architecture='约束→阻挡→实际选择→不可撤回后果',ending_weight=c['scenes'][2][1],audience_knowledge='先见控制，后知代价，最后看懂承担')
    review=ScreenplayReadinessReview(scope_id=name,source_pins=pins,revision='fixture-r1',historical=False,findings=tuple(ReadinessFinding(dimension=k,verdict='PASS',evidence=(source.key+'/scenes',),reason=reasons[k]) for k in sorted(READINESS_DIMENSIONS)),human_stakes_carrier=c['carrier'],emotional_counterline=c['counter'],affordance_audit='设计素材无历史声明，审已有物件机会',affordances=(DramaticAffordance(opportunity=c['object'],source_refs=(source.key,),evidence_limit='虚构，不作历史引文',thematic_relevance=c['counter'],decision='INCLUDE',reason='三次不同处理，物件意义发生变化'),))
    review_ref=keep('readiness',review)
    visual=keep('visual-bible',VisualBible(realism='可触摸材质与受控表达',palette=dict(dominant=['青灰','赭'],accent=['火光']),lighting=dict(philosophy='有来源且看清选择',fill='弱环境反射',faceShadowAllowed=True),image_character=dict(saturation='低',contrast='有局部明暗',highlight='有限高光',blackLevel='暗部保细节'),materials=dict(skin='非塑料',costume='织物有厚度',metal='有限磨损反光',environment='木石土'),atmosphere='夜湿气至黎明',camera_philosophy='关系变化驱动观看',forbidden=('奇幻发光',)))
    character=keep('character-visual',CharacterVisualSpec(character_identity=name+'-lead',revision='r1',dramatic_role=c['carrier'],visual_objective=c['intent'],silhouette='职业与任务区分体轴',costume_authority=c['costume']))
    costume_ref=keep('costume-bible',CostumeBible(character_identity=name+'-lead',visual_spec_ref=character,status_class='有责任但受限制',faction='同一时代材料语法',silhouette='任务体轴区分人物',layers=c['costume'],armor='护送有分层皮甲，文戏无甲',materials='布皮木依职业配置',colors='赭青灰低饱和，边缘细微明度差',ornament='沿边工艺，不加传奇装备',hero_support_hierarchy=c['scale'],historical_plausibility='设计素材无朝代声明；真实项目须置换有证据Canon',stylization_boundary='精致工艺允许，霓虹与不可能结构禁止',occupation_movement_wear=c['costume']))
    prop_ref=keep('prop',PropDesign(key=c['object'],category='FUNCTIONAL',function='可实际递交使用',relationship=c['counter'],material='按器物功能采用木金属布',scale='手与身体可操作',wear='接触边缘磨损',interaction='握住→让出→另一人承接',continuity='换场不重置状态',historical_basis='DESIGN_FIXTURE_ONLY'))
    colors=tuple(ColorKey(scene_id=s,hue_family='土赭青灰',warm_cool=['暖源冷暗部','冷夜与渐退暖漏光','冷灰中微暖晨光'][i],saturation='低饱和，手边物件留色相',value=['局部中值可读','天光分离轮廓','整体均值升高，暗衣不漂白'][i],contrast='保留触物动作，非一片黑',character_separation='衣边与背景错开，非永久金边',dramatic_function=c['scenes'][i][1],continuity_in='故事开始' if i==0 else '保留衣物物件变化',continuity_out='保留变化继续' if i<2 else '结果留在常态光中') for i,s in enumerate(scenes))
    style=StylizationReview(route=route,canon=HistoricalCanonPolicy(),hard_invariants=('身份权力因果不改','技术与器物功能不越界'),soft_realization=('精细工艺、层次材质轮廓',),expression_freedom=('有来源的光、深度与构图',),quality_evidence=dict(hierarchy=c['scale'],material_coherence='布皮木各有磨损',depth='门口前中后层',character_distinction='职业区别袖口站姿',lighting_compatibility='暗衣背景错开',composition='物件在关系之间',readability='手和物件轮廓分离'),cg_policy_applied=route=='stylized_cinematic_cg')
    film=FilmProductionDesign(scope_id=name,source_pins=pins,intent_ref=intent,route=route,visual_bible_ref=visual,stylization=style,style_position='克制可触摸的电影设计',environment_architecture='可站可走可递物的门口进深',materials='木石布皮统一层次',costume_armor=c['costume'],props=c['object'],crowd_army=c['scale'],weather='夜湿气→雨泥→黎明雨止，非历史声明',daytime_strategy='局部可见到公开后果',dirt_damage='污损跨场继承',motifs=c['object']+'三次功能变化，不反复特写',visual_hierarchy=c['scale'],color_script=colors,costume_bible_refs=(costume_ref,),prop_design_refs=(prop_ref,))
    film_ref=keep('film-design',film); entries=[];plans=[];prev=None;prev_ref=None
    def entry(dept,scope,owner,ref,summary):
        entries.append(DepartmentEntry(department=dept,scope_id=scope,owner=owner,artifact_ref=ref,intent_ref=intent,summary=summary))
    entry('film_design',name,'production-design',film_ref,'Film design/color')
    for i,s in enumerate(scenes):
        loc,action,performance=c['scenes'][i]; lamp=['室内油灯/灶火','门口漏光','东侧晨光'][i]
        state=CostumeState(character_identity=name+'-lead',scene_or_shot_id=s,changes=('仅有因果的状态改变',),bible_ref=costume_ref,previous_state_ref=prev_ref,costume=c['costume'],armor='战场皮甲/文戏无甲',equipment=(c['object'],),dirt='干尘' if i==0 else '衣摆泥污保留',dust='尘留接缝',water='干' if i==0 else '雨湿未干',sweat='领口汗痕',damage='旧裂保留',blood='无新增血迹',continuity_in=prev.continuity_out if prev else '初始状态',continuity_out=s+'物件衣物交接',change_causes=dict(dirt='出门踏入雨泥',water='雨湿外层') if i==1 else {})
        state_ref=keep(s+'-state',state); state_group=keep(s+'-costume',dict(states=[dump_contract(state)]))
        design=SceneProductionDesignPacket(scene_id=s,source_pins=pins,film_design_ref=film_ref,location=LocationDesignSpec(location=loc,revision='r1',space_purpose=action,spatial_hierarchy='任务中心在中层，两侧留通道',entrance_exit='A→B→C',major_anchors=(c['object'],'门柱'),materials='木土布',wear_state='常用处磨亮',storytelling_state=action,foreground='物件与手',midground='两人关系',background='出口与后果',light_sources=(lamp,)),geography_terrain='A内侧→B门槛→C外侧，压力与去路在C之外',zones=dict(A='内侧',B='门槛/窄口',C='外侧'),paths={'通路':('A','B'),'出口':('B','C')},entrances_exits=('A','C'),power_center='B',key_props={c['object']:'B'},character_start_end={name+'-lead':('A','B'),name+'-other':('B','C')},crowd_density=c['scale'],weather_atmosphere=['夜湿气','雨泥','雨止微湿'][i],daytime=['night interior','night exterior','dawn'][i],material_priority='手衣物关键物件先于装饰',color_key=colors[i],practical_sources={lamp:'A'},camera_zones=('A','C'),sound_zones=dict(B='人声接触',C='未见行动先闻声'),continuity_previous='初次建立' if i==0 else scenes[i-1]+'状态保留',continuity_next='移动与省略见transition' if i<2 else '后果保留',costume_state_refs=(state_ref,),visual_development_brief='未来概念图证明通路轮廓手部；本轮不生成。Performance/Blocking：'+performance)
        scene_ref=keep(s+'-design',design)
        light=LightingScript(scene_id=s,source_pins=pins,scene_design_ref=scene_ref,intent='选择和承担后果可见',motivated_sources=(lamp,),key_direction='A侧斜入，移到B衰减',fill='弱天光与墙反射让眼手可读',contrast='主侧有对比，暗部保留动作',value_hierarchy=colors[i].value,character_readability='暗衣与背景错开，非金边',background_separation='门口进深与轮廓负空间',practicals=lamp,atmosphere='雨尘不盖手',daytime_logic=design.daytime,color_relationship=colors[i].warm_cool,continuity_in=['夜局部光','继承门口漏光','明确省略至晨光'][i],continuity_out=['暖漏光向外衰减','夜声中止并省略到天亮','常态光中留后果'][i],cg_risks='防皮肤金属塑料高光' if route=='stylized_cinematic_cg' else None,camera_philosophy='动作改变关系再移注意',dominant_scale='双人中景至后果宽景',height_logic='任务视线高度，战场仅越遮挡',lens_family='自然透视保留门与人距离',movement='人物让位后有限横移显露去路',depth='前物中人后出口',axis='A-B-C同侧；过轴须重建',hero_restraint='不加决断仰拍与慢动作',environment_framing='门框证明谁能出去')
        light_ref=keep(s+'-light',light)
        dpd_ref=keep(s+'-dpd',formal['scene_dpds'][s] if formal else SceneDPD(scene_id=s,source_fingerprint=source.fingerprint,dramatic_purpose=action,conflict_condition=c['carrier'],power_structure='权力受他人任务与空间限制',direction=dict(objective=c['intent'],tactic='通过物件/通路争取改变',relationship_stance=c['counter'],internal_activation='MEDIUM',external_control='HIGH',public_private_context='向在场者做事，不播报给观众')))
        info=[dict(key=s+'-cause',information=action,focus='手与去路',change='选择影响别人'),dict(key=s+'-result',information=c['counter'],focus='变化后的空间',change='代价可见')]; shots=[s+'-a',s+'-b']
        transition=ShotTransition(from_shot=shots[0],to_shot=shots[1],end_state='物件/通路开始让出',opening_state='对方实际承接',cut_trigger='任务控制权转移',transition_type='action consequence cut',screen_direction='A向C左至右',axis='同侧不倒置门口',eyeline='由持物手到接物手',motion_continuity='松手前接镜不重复承接',composition_relation='中景到后果宽景，门柱仍在',sound_carry='carry',sound_intent='触物与呼吸，不追加配乐',time_relation='continuous',space_relation='同一门口关系',why_this_cut_exists='看见行动实际改变对方')
        plan=EditorialRhythmPlan(scene_ids=(s,),source_fingerprint=source.fingerprint,revision='r1',information_beats=info,coverage=[dict(key=x,beatIds=[info[n]['key']],duration=7 if n==0 else 5,durationBasis='DRAMATIC_INFORMATION',durationReason='等对象接到变化再切',purpose='SETUP' if n==0 else 'AFTERMATH') for n,x in enumerate(shots)],cuts=[dict(fromBeat=info[0]['key'],toBeat=info[1]['key'],reason='关系变化',newInformationOrRelation='承担后果')],establishing_need='先看懂入口物件',visual_contrast_rhythm='先压力后余波，不一句一反应',transitions=(transition,))
        coverage_ref=keep(s+'-coverage',plan);plans.append(plan)
        sound_ref=keep(s+'-sound',SourceSoundIntent(native_audio_policy='PREFERRED',diegetic=(c['object']+'接触声',),ambience=('风雨变化',),intentional_silence=('选择后不补解释',),continuity=('native优先，不默认TTS覆盖',)))
        for dept,owner,ref in [('scene_design','production-design',scene_ref),('costume','production-design',state_group),('lighting','cinematic-direction',light_ref),('performance','dramatic-performance-direction',dpd_ref),('coverage','shot-design',coverage_ref),('sound','cinematic-direction',sound_ref)]:entry(dept,s,owner,ref,performance if dept=='performance' else action)
        prev=state;prev_ref=state_ref
    seq=[]
    for i in range(2):
        a,b=plans[i:i+2]
        t=a.transitions[0].model_copy(update=dict(from_shot=a.coverage[-1].key,to_shot=b.coverage[0].key,transition_type='scene transition',time_relation='compressed continuous' if i==0 else 'explicit ellipsis',sound_carry='offscreen continuation' if i==0 else 'cut',sound_intent='门外动静续入' if i==0 else '夜声终止，晨声重建；不伪装瞬间天亮',end_state='前场衣物物件状态',opening_state='继承湿污和已改变关系',space_relation='内外经过门槛' if i==0 else '时间省略到外侧新站位',why_this_cut_exists='由选择到承担代价'))
        seq.append(keep('boundary'+str(i),EditorialRhythmPlan(scene_ids=scenes[i:i+2],source_fingerprint=source.fingerprint,revision='boundary',information_beats=(a.information_beats[-1],b.information_beats[0]),coverage=(a.coverage[-1],b.coverage[0]),establishing_need='重建时空关系',visual_contrast_rhythm='夜压力到晨后果',transitions=(t,))))
    sr=keep('self-review',dict(subjectKind='DESIGN_ONLY',verdict='PASS',reviewedArtifacts=[[e.artifact_ref.key,e.artifact_ref.fingerprint] for e in entries]+[[p.key,p.fingerprint] for p in seq],interfaceReviews=dict(costume_light='暗衣背景错开仍见手',layout_blocking='A-B-C可通；先让位过门',direction_axis='左至右，夜到晨显式省略',color_hierarchy='低饱和土赭青灰无英雄金光')))
    packet=DirectorDepartmentPacket(scope_id=name,scene_ids=scenes,source_pins=pins,route_ref=route_ref,intent_ref=intent,readiness_ref=review_ref,entries=tuple(entries),sequence_transition_refs=tuple(seq),self_review_ref=sr)
    return packet,review,current,artifacts
