from __future__ import annotations

from typing import Any, Protocol

from drama_plugin.contracts.asset import Asset, AssetBinding, AssetHierarchy
from drama_plugin.contracts.context import ContextBuildRequest, DramaContextPatch, DramaModelContext
from drama_plugin.contracts.generation import GenerationPlan, GenerationResult, GenerationState, GenerationTarget
from drama_plugin.contracts.history import ClaimVerification, HistoricalEvidence, HistoricalSource
from drama_plugin.contracts.media import ImageMetadata, Media, VideoMetadata
from drama_plugin.contracts.project import Character, Episode, Location, Project, Prop, Scene, Shot, Story


class ProjectProvider(Protocol):
    async def get_project(self, project_id: str) -> Project: ...
    async def get_story(self, story_id: str) -> Story: ...
    async def get_episode(self, episode_id: str) -> Episode: ...
    async def list_episodes(self, story_id: str) -> list[Episode]: ...
    async def get_scene(self, scene_id: str) -> Scene: ...
    async def list_scenes(self, episode_id: str) -> list[Scene]: ...
    async def get_shot(self, shot_id: str) -> Shot: ...
    async def list_shots(self, scene_id: str) -> list[Shot]: ...
    async def list_characters(self, resource_id: str) -> list[Character]: ...
    async def list_locations(self, resource_id: str) -> list[Location]: ...
    async def list_props(self, resource_id: str) -> list[Prop]: ...


class AssetProvider(Protocol):
    async def search_assets(self, query: str) -> list[Asset]: ...
    async def get_asset(self, asset_id: str) -> Asset: ...
    async def get_scene_asset_bindings(self, scene_id: str) -> list[AssetBinding]: ...
    async def get_shot_asset_bindings(self, shot_id: str) -> list[AssetBinding]: ...
    async def resolve_asset_hierarchy(
        self, *, scene_id: str | None = None, shot_id: str | None = None
    ) -> AssetHierarchy: ...


class HistoryProvider(Protocol):
    async def search_sources(self, query: str) -> list[HistoricalSource]: ...
    async def search_historical_event(self, query: str) -> list[HistoricalEvidence]: ...
    async def search_historical_person(self, query: str) -> list[HistoricalEvidence]: ...
    async def search_historical_location(self, query: str) -> list[HistoricalEvidence]: ...
    async def get_evidence(self, evidence_id: str) -> HistoricalEvidence: ...
    async def verify_claim(self, claim: str) -> ClaimVerification: ...


class GenerationProvider(Protocol):
    async def create_generation_plan(
        self, generation_target: GenerationTarget, resource_id: str, parameters: dict[str, Any] | None = None
    ) -> GenerationPlan: ...
    async def compile_generation_plan(self, plan_id: str) -> GenerationPlan: ...
    async def submit_generation(self, plan_id: str) -> GenerationState: ...
    async def get_generation_status(self, plan_id: str) -> GenerationState: ...
    async def get_generation_result(self, plan_id: str) -> GenerationResult: ...


class MediaProvider(Protocol):
    async def get_media(self, media_id: str) -> Media: ...
    async def list_asset_media(self, asset_id: str) -> list[Media]: ...
    async def get_image_metadata(self, media_id: str) -> ImageMetadata: ...
    async def get_video_metadata(self, media_id: str) -> VideoMetadata: ...


class ContextProvider(Protocol):
    async def build_context(self, request: ContextBuildRequest) -> DramaModelContext: ...
    async def refresh_context(
        self, request: ContextBuildRequest, current: DramaModelContext
    ) -> DramaContextPatch: ...
